// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, constant_identifier_names, non_constant_identifier_names

import 'dart:ffi' as ffi;

/// Bindings to 'hidapi.h'
class NativeLibrary {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  NativeLibrary(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  NativeLibrary.fromLookup(
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
          lookup)
      : _lookup = lookup;

  /// @brief Initialize the HIDAPI library.
  int hid_init() {
    return _hid_init();
  }

  late final _hid_initPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function()>>('hid_init');
  late final _hid_init = _hid_initPtr.asFunction<int Function()>();

  /// @brief Finalize the HIDAPI library.
  int hid_exit() {
    return _hid_exit();
  }

  late final _hid_exitPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function()>>('hid_exit');
  late final _hid_exit = _hid_exitPtr.asFunction<int Function()>();

  /// @brief Enumerate the HID Devices.
  ffi.Pointer<hid_device_info> hid_enumerate(
    int vendor_id,
    int product_id,
  ) {
    return _hid_enumerate(
      vendor_id,
      product_id,
    );
  }

  late final _hid_enumeratePtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<hid_device_info> Function(
              ffi.UnsignedShort, ffi.UnsignedShort)>>('hid_enumerate');
  late final _hid_enumerate = _hid_enumeratePtr
      .asFunction<ffi.Pointer<hid_device_info> Function(int, int)>();

  /// @brief Free an enumeration Linked List
  void hid_free_enumeration(
    ffi.Pointer<hid_device_info> devs,
  ) {
    return _hid_free_enumeration(
      devs,
    );
  }

  late final _hid_free_enumerationPtr = _lookup<
          ffi.NativeFunction<ffi.Void Function(ffi.Pointer<hid_device_info>)>>(
      'hid_free_enumeration');
  late final _hid_free_enumeration = _hid_free_enumerationPtr
      .asFunction<void Function(ffi.Pointer<hid_device_info>)>();

  /// @brief Open a HID device using a Vendor ID (VID), Product ID
  /// (PID) and optionally a serial number.
  ffi.Pointer<hid_device> hid_open(
    int vendor_id,
    int product_id,
    ffi.Pointer<ffi.WChar> serial_number,
  ) {
    return _hid_open(
      vendor_id,
      product_id,
      serial_number,
    );
  }

  late final _hid_openPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<hid_device> Function(ffi.UnsignedShort, ffi.UnsignedShort,
              ffi.Pointer<ffi.WChar>)>>('hid_open');
  late final _hid_open = _hid_openPtr.asFunction<
      ffi.Pointer<hid_device> Function(int, int, ffi.Pointer<ffi.WChar>)>();

  /// @brief Open a HID device by its path name.
  ffi.Pointer<hid_device> hid_open_path(
    ffi.Pointer<ffi.Char> path,
  ) {
    return _hid_open_path(
      path,
    );
  }

  late final _hid_open_pathPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<hid_device> Function(
              ffi.Pointer<ffi.Char>)>>('hid_open_path');
  late final _hid_open_path = _hid_open_pathPtr
      .asFunction<ffi.Pointer<hid_device> Function(ffi.Pointer<ffi.Char>)>();

  /// @brief Write an Output report to a HID device.
  int hid_write(
    ffi.Pointer<hid_device> dev,
    ffi.Pointer<ffi.UnsignedChar> data,
    int length,
  ) {
    return _hid_write(
      dev,
      data,
      length,
    );
  }

  late final _hid_writePtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<hid_device>,
              ffi.Pointer<ffi.UnsignedChar>, ffi.Size)>>('hid_write');
  late final _hid_write = _hid_writePtr.asFunction<
      int Function(
          ffi.Pointer<hid_device>, ffi.Pointer<ffi.UnsignedChar>, int)>();

  /// @brief Read an Input report from a HID device with timeout.
  int hid_read_timeout(
    ffi.Pointer<hid_device> dev,
    ffi.Pointer<ffi.UnsignedChar> data,
    int length,
    int milliseconds,
  ) {
    return _hid_read_timeout(
      dev,
      data,
      length,
      milliseconds,
    );
  }

  late final _hid_read_timeoutPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(
              ffi.Pointer<hid_device>,
              ffi.Pointer<ffi.UnsignedChar>,
              ffi.Size,
              ffi.Int)>>('hid_read_timeout');
  late final _hid_read_timeout = _hid_read_timeoutPtr.asFunction<
      int Function(
          ffi.Pointer<hid_device>, ffi.Pointer<ffi.UnsignedChar>, int, int)>();

  /// @brief Read an Input report from a HID device.
  int hid_read(
    ffi.Pointer<hid_device> dev,
    ffi.Pointer<ffi.UnsignedChar> data,
    int length,
  ) {
    return _hid_read(
      dev,
      data,
      length,
    );
  }

  late final _hid_readPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<hid_device>,
              ffi.Pointer<ffi.UnsignedChar>, ffi.Size)>>('hid_read');
  late final _hid_read = _hid_readPtr.asFunction<
      int Function(
          ffi.Pointer<hid_device>, ffi.Pointer<ffi.UnsignedChar>, int)>();

  /// @brief Set the device handle to be non-blocking.
  int hid_set_nonblocking(
    ffi.Pointer<hid_device> dev,
    int nonblock,
  ) {
    return _hid_set_nonblocking(
      dev,
      nonblock,
    );
  }

  late final _hid_set_nonblockingPtr = _lookup<
          ffi
          .NativeFunction<ffi.Int Function(ffi.Pointer<hid_device>, ffi.Int)>>(
      'hid_set_nonblocking');
  late final _hid_set_nonblocking = _hid_set_nonblockingPtr
      .asFunction<int Function(ffi.Pointer<hid_device>, int)>();

  /// @brief Send a Feature report to the device.
  int hid_send_feature_report(
    ffi.Pointer<hid_device> dev,
    ffi.Pointer<ffi.UnsignedChar> data,
    int length,
  ) {
    return _hid_send_feature_report(
      dev,
      data,
      length,
    );
  }

  late final _hid_send_feature_reportPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(
              ffi.Pointer<hid_device>,
              ffi.Pointer<ffi.UnsignedChar>,
              ffi.Size)>>('hid_send_feature_report');
  late final _hid_send_feature_report =
      _hid_send_feature_reportPtr.asFunction<
          int Function(
              ffi.Pointer<hid_device>, ffi.Pointer<ffi.UnsignedChar>, int)>();

  /// @brief Get a Feature report from the device.
  int hid_get_feature_report(
    ffi.Pointer<hid_device> dev,
    ffi.Pointer<ffi.UnsignedChar> data,
    int length,
  ) {
    return _hid_get_feature_report(
      dev,
      data,
      length,
    );
  }

  late final _hid_get_feature_reportPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(
              ffi.Pointer<hid_device>,
              ffi.Pointer<ffi.UnsignedChar>,
              ffi.Size)>>('hid_get_feature_report');
  late final _hid_get_feature_report = _hid_get_feature_reportPtr.asFunction<
      int Function(
          ffi.Pointer<hid_device>, ffi.Pointer<ffi.UnsignedChar>, int)>();

  /// @brief Get a input report from a HID device.
  int hid_get_input_report(
    ffi.Pointer<hid_device> dev,
    ffi.Pointer<ffi.UnsignedChar> data,
    int length,
  ) {
    return _hid_get_input_report(
      dev,
      data,
      length,
    );
  }

  late final _hid_get_input_reportPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(
              ffi.Pointer<hid_device>,
              ffi.Pointer<ffi.UnsignedChar>,
              ffi.Size)>>('hid_get_input_report');
  late final _hid_get_input_report = _hid_get_input_reportPtr.asFunction<
      int Function(
          ffi.Pointer<hid_device>, ffi.Pointer<ffi.UnsignedChar>, int)>();

  /// @brief Close a HID device.
  void hid_close(
    ffi.Pointer<hid_device> dev,
  ) {
    return _hid_close(
      dev,
    );
  }

  late final _hid_closePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<hid_device>)>>(
          'hid_close');
  late final _hid_close =
      _hid_closePtr.asFunction<void Function(ffi.Pointer<hid_device>)>();

  /// @brief Get The Manufacturer String from a HID device.
  int hid_get_manufacturer_string(
    ffi.Pointer<hid_device> dev,
    ffi.Pointer<ffi.WChar> string,
    int maxlen,
  ) {
    return _hid_get_manufacturer_string(
      dev,
      string,
      maxlen,
    );
  }

  late final _hid_get_manufacturer_stringPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<hid_device>, ffi.Pointer<ffi.WChar>,
              ffi.Size)>>('hid_get_manufacturer_string');
  late final _hid_get_manufacturer_string =
      _hid_get_manufacturer_stringPtr.asFunction<
          int Function(ffi.Pointer<hid_device>, ffi.Pointer<ffi.WChar>, int)>();

  /// @brief Get The Product String from a HID device.
  int hid_get_product_string(
    ffi.Pointer<hid_device> dev,
    ffi.Pointer<ffi.WChar> string,
    int maxlen,
  ) {
    return _hid_get_product_string(
      dev,
      string,
      maxlen,
    );
  }

  late final _hid_get_product_stringPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<hid_device>, ffi.Pointer<ffi.WChar>,
              ffi.Size)>>('hid_get_product_string');
  late final _hid_get_product_string =
      _hid_get_product_stringPtr.asFunction<
          int Function(ffi.Pointer<hid_device>, ffi.Pointer<ffi.WChar>, int)>();

  /// @brief Get The Serial Number String from a HID device.
  int hid_get_serial_number_string(
    ffi.Pointer<hid_device> dev,
    ffi.Pointer<ffi.WChar> string,
    int maxlen,
  ) {
    return _hid_get_serial_number_string(
      dev,
      string,
      maxlen,
    );
  }

  late final _hid_get_serial_number_stringPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<hid_device>, ffi.Pointer<ffi.WChar>,
              ffi.Size)>>('hid_get_serial_number_string');
  late final _hid_get_serial_number_string =
      _hid_get_serial_number_stringPtr.asFunction<
          int Function(ffi.Pointer<hid_device>, ffi.Pointer<ffi.WChar>, int)>();

  /// @brief Get The struct #hid_device_info from a HID device.
  ffi.Pointer<hid_device_info> hid_get_device_info(
    ffi.Pointer<hid_device> dev,
  ) {
    return _hid_get_device_info(
      dev,
    );
  }

  late final _hid_get_device_infoPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<hid_device_info> Function(
              ffi.Pointer<hid_device>)>>('hid_get_device_info');
  late final _hid_get_device_info = _hid_get_device_infoPtr.asFunction<
      ffi.Pointer<hid_device_info> Function(ffi.Pointer<hid_device>)>();

  /// @brief Get a string from a HID device, based on its string index.
  int hid_get_indexed_string(
    ffi.Pointer<hid_device> dev,
    int string_index,
    ffi.Pointer<ffi.WChar> string,
    int maxlen,
  ) {
    return _hid_get_indexed_string(
      dev,
      string_index,
      string,
      maxlen,
    );
  }

  late final _hid_get_indexed_stringPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<hid_device>, ffi.Int,
              ffi.Pointer<ffi.WChar>, ffi.Size)>>('hid_get_indexed_string');
  late final _hid_get_indexed_string =
      _hid_get_indexed_stringPtr.asFunction<
          int Function(
              ffi.Pointer<hid_device>, int, ffi.Pointer<ffi.WChar>, int)>();

  /// @brief Get a report descriptor from a HID device.
  int hid_get_report_descriptor(
    ffi.Pointer<hid_device> dev,
    ffi.Pointer<ffi.UnsignedChar> buf,
    int buf_size,
  ) {
    return _hid_get_report_descriptor(
      dev,
      buf,
      buf_size,
    );
  }

  late final _hid_get_report_descriptorPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int Function(
              ffi.Pointer<hid_device>,
              ffi.Pointer<ffi.UnsignedChar>,
              ffi.Size)>>('hid_get_report_descriptor');
  late final _hid_get_report_descriptor =
      _hid_get_report_descriptorPtr.asFunction<
          int Function(
              ffi.Pointer<hid_device>, ffi.Pointer<ffi.UnsignedChar>, int)>();

  /// @brief Get a string describing the last error which occurred.
  ffi.Pointer<ffi.WChar> hid_error(
    ffi.Pointer<hid_device> dev,
  ) {
    return _hid_error(
      dev,
    );
  }

  late final _hid_errorPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<ffi.WChar> Function(
              ffi.Pointer<hid_device>)>>('hid_error');
  late final _hid_error = _hid_errorPtr
      .asFunction<ffi.Pointer<ffi.WChar> Function(ffi.Pointer<hid_device>)>();

  /// @brief Get a runtime version of the library.
  ffi.Pointer<hid_api_version> hid_version() {
    return _hid_version();
  }

  late final _hid_versionPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<hid_api_version> Function()>>(
          'hid_version');
  late final _hid_version =
      _hid_versionPtr.asFunction<ffi.Pointer<hid_api_version> Function()>();

  /// @brief Get a runtime version string of the library.
  ffi.Pointer<ffi.Char> hid_version_str() {
    return _hid_version_str();
  }

  late final _hid_version_strPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function()>>(
          'hid_version_str');
  late final _hid_version_str =
      _hid_version_strPtr.asFunction<ffi.Pointer<ffi.Char> Function()>();
}

/// A structure to hold the version numbers.
final class hid_api_version extends ffi.Struct {
  /// < major version number
  @ffi.Int()
  external int major;

  /// < minor version number
  @ffi.Int()
  external int minor;

  /// < patch version number
  @ffi.Int()
  external int patch;
}

final class hid_device_ extends ffi.Opaque {}

/// @brief HID underlying bus types.
abstract class hid_bus_type {
  /// Unknown bus type
  static const int HID_API_BUS_UNKNOWN = 0;

  /// USB bus
  static const int HID_API_BUS_USB = 1;

  /// Bluetooth or Bluetooth LE bus
  static const int HID_API_BUS_BLUETOOTH = 2;

  /// I2C bus
  static const int HID_API_BUS_I2C = 3;

  /// SPI bus
  static const int HID_API_BUS_SPI = 4;
}

/// hidapi info structure
final class hid_device_info extends ffi.Struct {
  /// Platform-specific device path
  external ffi.Pointer<ffi.Char> path;

  /// Device Vendor ID
  @ffi.UnsignedShort()
  external int vendor_id;

  /// Device Product ID
  @ffi.UnsignedShort()
  external int product_id;

  /// Serial Number
  external ffi.Pointer<ffi.WChar> serial_number;

  /// Device Release Number in binary-coded decimal
  @ffi.UnsignedShort()
  external int release_number;

  /// Manufacturer String
  external ffi.Pointer<ffi.WChar> manufacturer_string;

  /// Product string
  external ffi.Pointer<ffi.WChar> product_string;

  /// Usage Page for this Device/Interface
  @ffi.UnsignedShort()
  external int usage_page;

  /// Usage for this Device/Interface
  @ffi.UnsignedShort()
  external int usage;

  /// The USB interface which this logical device represents.
  @ffi.Int()
  external int interface_number;

  /// Pointer to the next device
  external ffi.Pointer<hid_device_info> next;

  /// Underlying bus type
  @ffi.Int32()
  external int bus_type;
}

typedef hid_device = hid_device_;

const int HID_API_VERSION_MAJOR = 0;
const int HID_API_VERSION_MINOR = 15;
const int HID_API_VERSION_PATCH = 0;
const int HID_API_VERSION = 3840;
const String HID_API_VERSION_STR = '0.15.0';
const int HID_API_MAX_REPORT_DESCRIPTOR_SIZE = 4096;
